version: "3.8"

services:
  elsoc-app:
    image: ronakdotasara/elsoc-nith:latest
    container_name: elsoc-app
    expose:
      - "5173"
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: elsoc-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - elsoc-app
    networks:
      - web

networks:
  web:
    driver: bridge
